name: Check Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - uses: Gr1N/setup-poetry@v4
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: poetry --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make setup

      - name: run make check
        env:
          DJANGO_ENV: ci
        run: make check
